print ("Nama : Katon Adiluhung")
print ("NIM  : I0322063")
print ("Asal : Blora, Jawa Tengah")
print ("====================================")
print ("Saya berasal dari Kota Blora")
print ("Blora merupakan sebuah kabupaten yang ada di Provinsi Jawa Tengah")
print ("Kota ini memiliki suhu udara dan cuaca yang panas karena terik matahari")
print ("Blora merupakan kota dengan kekayaan alam berupa hutan pohon jati sehingga banyak sekali penghasil kerajinan ataupun meubel di kota ini")
print ("Selain itu, Blora merupakan kota penghasil minyak di Indonesia, tepatnya di Kecamatan Cepu")
print ("Kecamatan Cepu memegang peranan penting bagi Kota Blora dikarenakan kekayaan minyaknya yang melimpah")
print ("============================================================================================================================")
print ("Harapan saya menjadi lulusan Teknik Industri adalah saya mampu menerapkan ilmu yang telah saya dapat pada dunia kerja nantinya ")
print ("________________________________________________________________________________________________________________________________________")
